#!/bin/sh
set -e
export LC_ALL=C
export CFLAGS="-O3 -D_FORTIFY_SOURCE=0 -fomit-frame-pointer -finline-functions-called-once -fmerge-constants -ftree-dce -ftree-dse -ftree-loop-vectorize -ftree-vectorize -fdce -fdse -march=znver3 -DNDEBUG"
export CXXFLAGS="-O3 -D_FORTIFY_SOURCE=0 -fomit-frame-pointer -finline-functions-called-once -fmerge-constants -ftree-dce -ftree-dse -ftree-loop-vectorize -ftree-vectorize -fdce -fdse -march=znver3 -DNDEBUG"

#scripts/fribidi-config
#scripts/fribidi-build "$@"
scripts/libplacebo-config
scripts/libplacebo-build "$@"
scripts/libass-config
scripts/libass-build "$@"
scripts/ffmpeg-config
scripts/ffmpeg-build "$@"
scripts/mpv-config
scripts/mpv-build "$@"
